# Generated by Django 4.1.5 on 2023-01-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'staff'},
        ),
    ]
