# Generated by Django 4.1.5 on 2023-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='chief',
            field=models.CharField(default='Jessica Patterson', max_length=50),
            preserve_default=False,
        ),
    ]
